trigger:
- main
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
    tasks: 'clean testDebugUnitTest assembleDebug'
